### ISSUE TITLE
Apply the featured engineering to new data to make predictions?

### ISSUE THREAD

**Issue by chitown88** [Muhammad4hmed/Ghalat-Machine-Learning#1]
I'm using the auto feature engineering feature to create the new_features then to train my model. Now that I have new data that I want to predict on, how would I go about to apply that process to my new data so that the trained model doesn't mismatch in its core dimensions with the new data?

**Comment by Muhammad4hmed** [comment]
Hi, yes this an issue which will be resolved in next updates. for now, you have to make a seprate object of GML everytime you do training.

**Comment by jason022085** [comment]
Hi,
When I doing "from GML.Ghalat_Machine_Learning import Ghalat_Machine_Learning"
There is a error AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_is_tf_1'
I have tried pip install --upgrade keras , but it's still not working.
Could you tell me which version of keras fit GML ,please ?

**Comment by Muhammad4hmed** [comment]
hi @jason022085, any latest version of keras should work.
have you tried upgrading GML?

**Comment by chitown88** [comment]
It’s an issue with the latest version of Keras and tensorflow. Uninstall your Kera’s and then reinstall a previous version of Keras.

**Comment by chitown88** [comment]
@jason022085 I had the same issue. You need to downgrade your Keras version.

**Comment by jason022085** [comment]
> @jason022085 I had the same issue. You need to downgrade your Keras version.

Thanks a lots.
I use Keras==2.1.0 works 
And I offer an information that keras==2.0.0 doesn't work with lastest GML.

**Comment by chitown88** [comment]
@jason022085 so did that work? I’ll have to check my versions.

**Comment by Muhammad4hmed** [comment]
@chitown88 thank you for your contribution :) I will resolve this issue in next update :)

**Comment by jason022085** [comment]
The classification demo document works in the following environment : 
category_encoders==2.1.0
tensorflow==2.1.0
keras==2.3.1
GML==2.0.4

I think the core problem is not about the version of GML, but the specific version of keras corresponding to the lastest tensorflow.
