### ISSUE TITLE
Problem with NLP

### ISSUE THREAD

**Issue by harry418** [Muhammad4hmed/Ghalat-Machine-Learning#10]
tokenizer_name is not defined in tokenize.
AttributeError                          Traceback (most recent call last)
<ipython-input-24-112b4e0048d3> in <module>()
----> 1 tokenizedX = nlp.tokenize(cleanX.values)

/usr/local/lib/python3.6/dist-packages/GML/NLP.py in tokenize(self, text)
    580     Return: Tokenized
    581     """
--> 582     tokenizer = AutoTokenizer.from_pretrained(self.tokenizer_name)
    583     encoded = tokenizer.batch_encode_plus(
    584       text,

AttributeError: 'AutoNLP' object has no attribute 'tokenizer_name'

**Comment by Muhammad4hmed** [comment]
Please make sure you called the set_params() function before tokenizing or modeling.

Just like in this notebook: https://github.com/Muhammad4hmed/GML/blob/master/DEMO/AutoTextClassification.ipynb

**Comment by Muhammad4hmed** [comment]
Closing this issue assuming it's solved. if not, feel free to reopen.
