### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by Rubix982** [Muhammad4hmed/Ghalat-Machine-Learning#2]
Hello!

I would like to like create this project locally in a virtual environment with all the dependencies, but there is not `requirements.txt` here.  Please create one. Thanks!

**Comment by Muhammad4hmed** [comment]
Hi, in setup.py, the dependencies are mentioned.
` install_requires=['scikit-learn','xgboost','catboost','Keras','lightgbm']`
You can install GML on any environment simply by pip:
`pip install GML`
this will install all the dependencies along with GML.

**Comment by Rubix982** [comment]
That's fine, I got that, but in case of any failures or weird error messages that might pop up in the dependencies themselves, it would help to note down which dependency is breaking. Keeping around version numbers can be useful for debugging later on. By default, I'm supposing pip just picks up the latest versions for these packages, right?

**Comment by Muhammad4hmed** [comment]
GML always requires the latest version of above mentioned dependencies.
