### ISSUE TITLE
feature engineering problems

### ISSUE THREAD

**Issue by prashanthGit945** [Muhammad4hmed/Ghalat-Machine-Learning#7]
from GML import FeatureEngineering

fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode',cat_cols=3,
numeric_cols=11,
method_num='Mean', encode_data=True, 
                        normalize=True, remove_outliers=True, 
                        new_features=True, feateng_steps=2 ) # feateng_steps = 0 for features selection without feature creation

X_new, y, test = fe.get_new_data()

==============================
Handling Missing Data
==============================
There is missing data
'int' object is not iterable
==============================

==============================
Encoding Data
==============================
Success
Data Encoded
==============================

==============================
Transforming Data
==============================
Data Transformed
==============================

==============================
Handling Outliers
==============================
Before outlier removal 
interquartile range: 0.919066837284749
upper_inner_fence: 10.106504611810337
lower_inner_fence: 6.430237262671341
upper_outer_fence: 11.48510486773746
lower_outer_fence: 5.051637006744217
percentage of records out of inner fences: 5.62
percentage of records out of outer fences: 0.22
length of input dataframe: 6313
length of new dataframe after outlier removal: 5958
After outlier removal 
==============================

==============================
Creating New Features with Features Selection
==============================
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-cc527205e4bc> in <module>
      1 from GML import FeatureEngineering
      2 
----> 3 fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode',cat_cols=3,
      4 numeric_cols=11,
      5 method_num='Mean', encode_data=True,

~\Anaconda3\lib\site-packages\GML\FEATURE_ENGINEERING.py in __init__(self, data, label, fill_missing_data, method_cat, method_num, drop, cat_cols, numeric_cols, thresh_cat, thresh_numeric, encode_data, method, thresh, normalize, method_transform, thresh_numeric_transform, remove_outliers, qu_fence, new_features, task, test_data, verbose, feateng_steps)
    156                 except:
    157                     pass
--> 158                 X = afc.fit_transform(X, y)
    159                 if not test_data == None:
    160                     test_data = afc.transform(test_data)

~\Anaconda3\lib\site-packages\GML\AUTO_FEATURE_ENGINEERING\autofeat.py in fit_transform(self, X, y)
    245         cols = [str(c) for c in X.columns] if isinstance(X, pd.DataFrame) else []
    246         # check input variables
--> 247         X, target = check_X_y(X, y, y_numeric=self.problem_type == "regression", dtype=None)
    248         if not cols:
    249             # the additional zeros in the name are because of the variable check in _generate_features,

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
    793         raise ValueError("y cannot be None")
    794 
--> 795     X = check_array(X, accept_sparse=accept_sparse,
    796                     accept_large_sparse=accept_large_sparse,
    797                     dtype=dtype, order=order, copy=copy,

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    642 
    643         if force_all_finite:
--> 644             _assert_all_finite(array,
    645                                allow_nan=force_all_finite == 'allow-nan')
    646 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
    102     elif X.dtype == np.dtype('object') and not allow_nan:
    103         if _object_dtype_isnan(X).any():
--> 104             raise ValueError("Input contains NaN")
    105 
    106 

ValueError: Input contains NaN

**Comment by Muhammad4hmed** [comment]
Hi, you have passed the wrong arguments, the arguments you passed are:
cat_cols and numeric_cols as numbers but you have to pass a list of corresponding numerical and categorical columns, for example, if my column B and D is categorical then I will pass cat_cols = ['B', 'D'] and the respecting numeric_cols. if you don't pass any column, it will detect categorical and numerical columns by itself.
secondly, through your label column, 'Selling_Price', it seems that it's a regression task, so don't forget to pass the "task = 'regression' " argument.
Functions description is available inside each function.

**Comment by prashanthGit945** [comment]
what about missing values, how to fill/treat them  it shows there is nans in the data I already passed fill_missing_values =true but no result

**Comment by Muhammad4hmed** [comment]
yes this error is because of the wrong arguments

**Comment by prashanthGit945** [comment]
what is the solution for it how to pass arguments

**Comment by Muhammad4hmed** [comment]
try this:

```python
fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode',
method_num='Mean', encode_data=True,
normalize=True, remove_outliers=True,
new_features=True, feateng_steps=2, task = 'regression' ) 

X_new, y, test = fe.get_new_data()
```

**Comment by prashanthGit945** [comment]
fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode',
method_num='Mean', encode_data=True,
normalize=True, remove_outliers=True,
new_features=True, feateng_steps=2, task = 'regression' ) 

X_new, y, test = fe.get_new_data()

==============================
Handling Missing Data
==============================
There is missing data
could not convert string to float: 'BRAE2NF6JA5GUEXG'
==============================



==============================
Encoding Data
==============================
Success
Data Encoded
==============================



==============================
Transforming Data
==============================
Data Transformed
==============================



==============================
Handling Outliers
==============================
Before outlier removal 
interquartile range: 0.919066837284749
upper_inner_fence: 10.106504611810337
lower_inner_fence: 6.430237262671341
upper_outer_fence: 11.48510486773746
lower_outer_fence: 5.051637006744217
percentage of records out of inner fences: 5.62
percentage of records out of outer fences: 0.22
length of input dataframe: 6313
length of new dataframe after outlier removal: 5958
After outlier removal 
==============================



==============================
Creating New Features with Features Selection
==============================
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-dd87e018e916> in <module>
----> 1 fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode',
      2 method_num='Mean', encode_data=True,
      3 normalize=True, remove_outliers=True,
      4 new_features=True, feateng_steps=2, task = 'regression' ) 
      5 

~\Anaconda3\lib\site-packages\GML\FEATURE_ENGINEERING.py in __init__(self, data, label, fill_missing_data, method_cat, method_num, drop, cat_cols, numeric_cols, thresh_cat, thresh_numeric, encode_data, method, thresh, normalize, method_transform, thresh_numeric_transform, remove_outliers, qu_fence, new_features, task, test_data, verbose, feateng_steps)
    166                 except:
    167                     pass
--> 168                 X = afc.fit_transform(X, y)
    169                 if not test_data == None:
    170                     test_data = afc.transform(test_data)

~\Anaconda3\lib\site-packages\GML\AUTO_FEATURE_ENGINEERING\autofeat.py in fit_transform(self, X, y)
    245         cols = [str(c) for c in X.columns] if isinstance(X, pd.DataFrame) else []
    246         # check input variables
--> 247         X, target = check_X_y(X, y, y_numeric=self.problem_type == "regression", dtype=None)
    248         if not cols:
    249             # the additional zeros in the name are because of the variable check in _generate_features,

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
    793         raise ValueError("y cannot be None")
    794 
--> 795     X = check_array(X, accept_sparse=accept_sparse,
    796                     accept_large_sparse=accept_large_sparse,
    797                     dtype=dtype, order=order, copy=copy,

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    642 
    643         if force_all_finite:
--> 644             _assert_all_finite(array,
    645                                allow_nan=force_all_finite == 'allow-nan')
    646 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
    102     elif X.dtype == np.dtype('object') and not allow_nan:
    103         if _object_dtype_isnan(X).any():
--> 104             raise ValueError("Input contains NaN")
    105 
    106 

ValueError: Input contains NaN

still, it's getting the same error

**Comment by prashanthGit945** [comment]
![Screenshot 2020-12-01 202216](https://user-images.githubusercontent.com/45137286/100756226-09e5a500-3413-11eb-92bb-99e0627cfecd.png)
![Screenshot 2020-12-01 202249](https://user-images.githubusercontent.com/45137286/100756234-0baf6880-3413-11eb-9344-bacff564c70a.png)

**Comment by prashanthGit945** [comment]
this is my data and I am getting a lot of errors

**Comment by Muhammad4hmed** [comment]
first make list of categorical columns and numerical columns which are in your data and then pass that list to FE.
try this:

```python
cat_cols = ['Product_id', 'instock_date', 'Customer_name', 'Loyalty_Customer', 'Product_Category'] 
numeric_cols = ['Stall_no', 'Market_Category', 'Grade', 'Demand', 'Discount_avail', 'charges_1', 'charges_2(%)', 'Minimum_price', 'Maximum_price']


fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode', cat_cols = cat_cols, numeric_cols = numeric_cols,
method_num='Mean', encode_data=True,
normalize=True, remove_outliers=True,
new_features=True, feateng_steps=2, task = 'regression' ) 

X_new, y, test = fe.get_new_data()
```

Please recheck the column names, spaces etc

**Comment by prashanthGit945** [comment]
Unique values in Product_id 6368
Unique values in Stall_no 50
Unique values in instock_date 5350
Unique values in Market_Category 248
Unique values in Customer_name 5900
Unique values in Loyalty_customer 2
Unique values in Product_Category 10
Unique values in Grade 4
Unique values in Demand 100
Unique values in Discount_avail 2
Unique values in charges_1 487
Unique values in charges_2 (%) 17
Unique values in Minimum_price 4236
Unique values in Maximum_price 4618
Unique values in Selling_Price 6321



train.isnull().sum()
Product_id            0
Stall_no              5
instock_date          0
Market_Category       0
Customer_name       206
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       37
charges_1           197
charges_2           204
Minimum_price        38
Maximum_price       340
Selling_Price         0

==============================
Handling Missing Data
==============================
There is missing data
'Loyalty_Customer'
==============================



==============================
Encoding Data
==============================
Success
Data Encoded
==============================



==============================
Transforming Data
==============================
Data Transformed
==============================



==============================
Handling Outliers
==============================
Before outlier removal 
interquartile range: 0.919066837284749
upper_inner_fence: 10.106504611810337
lower_inner_fence: 6.430237262671341
upper_outer_fence: 11.48510486773746
lower_outer_fence: 5.051637006744217
percentage of records out of inner fences: 5.62
percentage of records out of outer fences: 0.22
length of input dataframe: 6313
length of new dataframe after outlier removal: 5958
After outlier removal 
==============================



==============================
Creating New Features with Features Selection
==============================
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-7ab57959913a> in <module>
      4 
      5 
----> 6 fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode', cat_cols = cat_cols, numeric_cols = numeric_cols,
      7 method_num='Mean', encode_data=True,
      8 normalize=True, remove_outliers=True,

~\Anaconda3\lib\site-packages\GML\FEATURE_ENGINEERING.py in __init__(self, data, label, fill_missing_data, method_cat, method_num, drop, cat_cols, numeric_cols, thresh_cat, thresh_numeric, encode_data, method, thresh, normalize, method_transform, thresh_numeric_transform, remove_outliers, qu_fence, new_features, task, test_data, verbose, feateng_steps)
    166                 except:
    167                     pass
--> 168                 X = afc.fit_transform(X, y)
    169                 if not test_data == None:
    170                     test_data = afc.transform(test_data)

~\Anaconda3\lib\site-packages\GML\AUTO_FEATURE_ENGINEERING\autofeat.py in fit_transform(self, X, y)
    245         cols = [str(c) for c in X.columns] if isinstance(X, pd.DataFrame) else []
    246         # check input variables
--> 247         X, target = check_X_y(X, y, y_numeric=self.problem_type == "regression", dtype=None)
    248         if not cols:
    249             # the additional zeros in the name are because of the variable check in _generate_features,

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
    793         raise ValueError("y cannot be None")
    794 
--> 795     X = check_array(X, accept_sparse=accept_sparse,
    796                     accept_large_sparse=accept_large_sparse,
    797                     dtype=dtype, order=order, copy=copy,

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    642 
    643         if force_all_finite:
--> 644             _assert_all_finite(array,
    645                                allow_nan=force_all_finite == 'allow-nan')
    646 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
    102     elif X.dtype == np.dtype('object') and not allow_nan:
    103         if _object_dtype_isnan(X).any():
--> 104             raise ValueError("Input contains NaN")
    105 
    106 

ValueError: Input contains NaN

I renamed column names, no spaces and symbols do not present now
still error

**Comment by Muhammad4hmed** [comment]
its "Loyalty_customer" not "Loyalty_Customer", its case sensitive.

**Comment by prashanthGit945** [comment]
ok i got that point i changed
==============================
Handling Missing Data
==============================
There is missing data
Missing data Handled
==============================



==============================
Encoding Data
==============================
Success
Data Encoded
==============================



==============================
Transforming Data
==============================
Data Transformed
==============================



==============================
Handling Outliers
==============================
Before outlier removal 
interquartile range: 0.919066837284749
upper_inner_fence: 10.106504611810337
lower_inner_fence: 6.430237262671341
upper_outer_fence: 11.48510486773746
lower_outer_fence: 5.051637006744217
percentage of records out of inner fences: 5.62
percentage of records out of outer fences: 0.22
length of input dataframe: 6313
length of new dataframe after outlier removal: 5958
After outlier removal 
==============================



==============================
Creating New Features with Features Selection
==============================
[GML] The 2 step feature engineering process could generate up to 4851 features.
[GML] With 5958 data points this new feature matrix would use about 0.12 gb of space.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-6375c2508371> in <module>
      4 
      5 
----> 6 fe = FeatureEngineering(train,'Selling_Price', fill_missing_data=True,method_cat='Mode', cat_cols = cat_cols, numeric_cols = numeric_cols,
      7 method_num='Mean', encode_data=True,
      8 normalize=True, remove_outliers=True,

~\Anaconda3\lib\site-packages\GML\FEATURE_ENGINEERING.py in __init__(self, data, label, fill_missing_data, method_cat, method_num, drop, cat_cols, numeric_cols, thresh_cat, thresh_numeric, encode_data, method, thresh, normalize, method_transform, thresh_numeric_transform, remove_outliers, qu_fence, new_features, task, test_data, verbose, feateng_steps)
    166                 except:
    167                     pass
--> 168                 X = afc.fit_transform(X, y)
    169                 if not test_data == None:
    170                     test_data = afc.transform(test_data)

~\Anaconda3\lib\site-packages\GML\AUTO_FEATURE_ENGINEERING\autofeat.py in fit_transform(self, X, y)
    294             target_sub = target.copy()
    295         # generate features
--> 296         df_subs, self.feature_formulas_ = engineer_features(df_subs, self.feateng_cols_, _parse_units(self.units, verbose=self.verbose),
    297                                                             self.feateng_steps, self.transformations, self.verbose)
    298         # select predictive features

~\Anaconda3\lib\site-packages\GML\AUTO_FEATURE_ENGINEERING\feateng.py in engineer_features(df_org, start_features, units, max_steps, transformations, verbose)
    133         return df_org, feature_pool
    134     # get a copy of the dataframe - this is where all the features will be added
--> 135     df = pd.DataFrame(df_org.copy(), dtype=np.float32)
    136 
    137     def apply_transformations(features_list):

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    461                 return
    462 
--> 463             mgr = self._init_mgr(
    464                 data, axes=dict(index=index, columns=columns), dtype=dtype, copy=copy
    465             )

~\Anaconda3\lib\site-packages\pandas\core\generic.py in _init_mgr(cls, mgr, axes, dtype, copy)
    225             # avoid further copies if we can
    226             if len(mgr.blocks) > 1 or mgr.blocks[0].values.dtype != dtype:
--> 227                 mgr = mgr.astype(dtype=dtype)
    228         return mgr
    229 

~\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in astype(self, dtype, copy, errors)
    593         self, dtype, copy: bool = False, errors: str = "raise"
    594     ) -> "BlockManager":
--> 595         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    596 
    597     def convert(

~\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, align_keys, **kwargs)
    404                 applied = b.apply(f, **kwargs)
    405             else:
--> 406                 applied = getattr(b, f)(**kwargs)
    407             result_blocks = _extend_blocks(applied, result_blocks)
    408 

~\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors)
   2098 
   2099         # delegate
-> 2100         return super().astype(dtype=dtype, copy=copy, errors=errors)
   2101 
   2102     def _can_hold_element(self, element: Any) -> bool:

~\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors)
    593             vals1d = values.ravel()
    594             try:
--> 595                 values = astype_nansafe(vals1d, dtype, copy=True)
    596             except (ValueError, TypeError):
    597                 # e.g. astype_nansafe can fail on object-dtype of strings

~\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy, skipna)
    937             return arr.astype(dtype)
    938 
--> 939         raise TypeError(f"cannot astype a datetimelike from [{arr.dtype}] to [{dtype}]")
    940 
    941     elif is_timedelta64_dtype(arr):

TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float32]

**Comment by prashanthGit945** [comment]
what to do with datetime feature

**Comment by Muhammad4hmed** [comment]
GML currently don't handle date time columns (I will update it in few days) for now, you can drop it

**Comment by prashanthGit945** [comment]
ok, thank you so much for your valuable time spent with me to solve this ...
